apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: loki-gateway
  namespace: monitoring
spec:
  gatewayClassName: cilium
  listeners:
  - name: https
    hostname: logs.holton.xyz
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - name: logs-holton-xyz-cert
        kind: Secret
    allowedRoutes:
      namespaces:
        from: Same
