apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: jth-gg-gateway
  namespace: jth-gg
spec:
  gatewayClassName: cilium
  listeners:
  - name: https
    hostname: jth.gg
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - name: jth-gg-cert
        kind: Secret
    allowedRoutes:
      namespaces:
        from: Same
