apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: holton-prod-postgres-1
  namespace: cnpg-system
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16

  bootstrap:
    initdb:
      database: app
      owner: app

  storage:
    size: 20Gi
    storageClass: nfs-csi

  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "2"

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "768MB"
      work_mem: "4MB"
      maintenance_work_mem: "64MB"

  monitoring:
    enablePodMonitor: false
